name: publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: verifyimg
            asset_name: verifyimg-linux-amd64
          - os: macos-latest
            artifact_name: verifyimg
            asset_name: verifyimg-macos-amd64
          - os: windows-latest
            artifact_name: verifyimg.exe
            asset_name: verifyimg-windows-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
